version: "3.8"


networks:
  monitoring:
    driver: bridge

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - monitoring

#  app:
#    container_name: msi_backend
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    ports:
#      - "8086:8086"
#    stdin_open: true
#    tty: true
#    depends_on:
#      - mariadb
#    volumes:
#      - log_data:/logs
#    networks:
#      - monitoring

volumes:
  mariadb_data:
  log_data: